# Generated by Django 3.2.3 on 2021-05-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210529_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lecture',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='courses.lecture'),
            preserve_default=False,
        ),
    ]
