# Generated by Django 3.2.3 on 2021-06-04 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_auto_20210604_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='user',
        ),
        migrations.AddField(
            model_name='solution',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='accounts.user'),
            preserve_default=False,
        ),
    ]
