# Generated by Django 3.2.3 on 2021-06-04 03:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210604_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='status',
        ),
        migrations.AddField(
            model_name='solution',
            name='rating',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='solution',
            name='status',
            field=models.CharField(choices=[('performed', 'Performed'), ('not_performed', 'Not performed')], default='not_performed', max_length=15),
        ),
    ]
