# Generated by Django 3.2.3 on 2021-05-29 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_homework_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.BooleanField(choices=[(1, 'Performed'), (0, 'Not performed')], default=0),
        ),
    ]
