# Generated by Django 3.2.3 on 2021-06-04 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210604_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.solution'),
        ),
    ]
