# Generated by Django 3.2.3 on 2021-05-29 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_homework_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='status',
            field=models.CharField(choices=[('performed', 'Performed'), ('not_performed', 'Not performed')], default='not_performed', max_length=15),
        ),
    ]
