# Generated by Django 3.2.3 on 2021-05-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210528_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner',
        ),
    ]
